version: '2'
services:
  sentinel1:
    image: 'docker.iranrepo.ir/bitnami/redis-sentinel:6.2.12'
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - REDIS_MASTER_HOST=master-redis
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_PORT_NUMBER=26379
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '26379'
    networks:
      - compose-net

networks:
  compose-net:
    name: sentinel
    external: true